services:
  mockServer:
    image: mockserver/mockserver:7.5.0@sha256:a268c84e2e3a8a0682b9771f37ed0f201ea9ec921ef05b945be80e52eedf6f55
    ports:
      - 1080:1080
    environment:
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json
    volumes:
      - type: bind
        source: ./mockserver-config
        target: /config
